export default {
  getCompanies() {
    return [
      {
        companyId: "1",
        name: "Apple",
        score: "94",
        hqLocation: "Cupertino, USA",
        revenueSize: "$300M",
        industry: "Technology",
        insight: "Apple, known for its innovative products like the iPhone, iPad, and Mac, has played a pivotal role in shaping the tech industry. Its design-driven approach and ecosystem of devices and services have garnered a massive global following.",
      },
      {
        companyId: "2",
        name: "The Coca-Cola Company",
        score: "76",
        hqLocation: "Atlanta, USA",
        revenueSize: "$35M",
        industry: "Beverages",
        insight: "The Coca-Cola Company, a beverage industry leader, is known for its iconic soft drink and a wide portfolio of beverages. Its brand recognition and global reach make it a symbol of refreshment.",
      },
      {
        companyId: "3",
        name: "Johnson & Johnson",
        score: "88",
        hqLocation: "New Brunswick, USA",
        revenueSize: "$180M",
        industry: "Healthcare",
        insight: "Johnson & Johnson, a pharmaceutical and consumer goods conglomerate, is known for its diverse range of products, from medical devices and pharmaceuticals to baby care items. Its commitment to health and wellness spans generations.",
      },
      {
        companyId: "4",
        name: "Tesla",
        score: "95",
        hqLocation: "Palo Alto, USA",
        revenueSize: "$20M",
        industry: "Electric Car",
        insight: "Tesla, founded by Elon Musk, is a pioneer in the electric car industry. Known for its innovative technology and performance, Tesla's vehicles have redefined the perception of electric transportation.",
      },
      {
        companyId: "5",
        name: "BMW",
        score: "88",
        hqLocation: "Munich, Germany",
        revenueSize: "$16M",
        industry: "Car",
        insight: "BMW is a luxury car manufacturer celebrated for its high-performance and elegant vehicles. The brand represents a blend of driving pleasure, luxury, and cutting-edge technology.",
      },
      {
        companyId: "6",
        name: "Volkswagen",
        score: "80",
        hqLocation: "Wolfsburg, Germany",
        revenueSize: "$14M",
        industry: "Car",
        insight: "Volkswagen is a German automaker known for its wide range of vehicles, from compact cars to luxury models. The company has a global presence and has been at the forefront of automotive engineering.",
      },
      {
        companyId: "7",
        name: "Hyundai",
        score: "79",
        hqLocation: "Seoul, South Korea",
        revenueSize: "$9M",
        industry: "Car",
        insight: "Hyundai is a major player in the global car market, known for its value-packed vehicles. The company's diverse lineup appeals to a wide range of consumers, and it has shown a growing focus on sustainability.",
      },
      {
        companyId: "8",
        name: "Microsoft",
        score: "90",
        hqLocation: "Redmond, USA",
        revenueSize: "$270M",
        industry: "Technology",
        insight: "Microsoft, a software and technology behemoth, is known for its Windows operating system, Office suite, and Azure cloud platform. The company's products have had a profound impact on personal and enterprise computing.",
      },
      {
        companyId: "9",
        name: "Procter & Gamble",
        score: "82",
        hqLocation: "Cincinnati, USA",
        revenueSize: "$150M",
        industry: "Consumer Goods",
        insight: "Procter & Gamble is a multinational consumer goods corporation behind popular brands like Tide, Pampers, and Gillette. Its products touch everyday lives around the world, making it a household name.",
      },
      {
        companyId: "10",
        name: "Nissan",
        score: "72",
        hqLocation: "Yokohama, Japan",
        revenueSize: "$11M",
        industry: "Car",
        insight: "Nissan is a global automobile manufacturer recognized for its innovation and stylish designs. The company has contributed to advancements in electric and autonomous vehicle technology.",
      },
      {
        companyId: "11",
        name: "Walmart",
        score: "78",
        hqLocation: "Bentonville, USA",
        revenueSize: "$250M",
        industry: "Retail",
        insight: "Walmart, a retail giant, operates a vast network of stores and e-commerce platforms globally. Its focus on low prices and wide product selection has made it a significant player in the retail landscape.",
      },
      {
        companyId: "12",
        name: "Amazon",
        score: "88",
        hqLocation: "Seattle, USA",
        revenueSize: "$280M",
        industry: "E-commerce",
        insight: "Amazon, the e-commerce giant founded by Jeff Bezos, has transformed online shopping and cloud computing. Its vast marketplace, Prime membership, and Amazon Web Services have redefined consumer behavior and digital infrastructure.",
      },
      {
        companyId: "13",
        name: "Netflix",
        score: "89",
        hqLocation: "Los Gatos, USA",
        revenueSize: "$25M",
        industry: "Entertainment",
        insight: "Netflix, a streaming entertainment powerhouse, has transformed how people consume media. Its original content, user-friendly interface, and global availability have made it a dominant force in the entertainment industry.",
      },
      {
        companyId: "14",
        name: "Google",
        score: "96",
        hqLocation: "Mountain View, USA",
        revenueSize: "$320M",
        industry: "Technology",
        insight: "Google, now a subsidiary of Alphabet Inc., dominates the online search and advertising space. Beyond its core search engine, Google has expanded into areas like Android, YouTube, and cloud services.",
      },
      {
        companyId: "15",
        name: "Facebook",
        score: "84",
        hqLocation: "Menlo Park, USA",
        revenueSize: "$150M",
        industry: "Technology",
        insight: "Facebook, now Meta Platforms, is a social media titan that has redefined online communication. Its platforms, including Facebook, Instagram, and WhatsApp, have transformed the way people connect and share information.",
      },
      {
        companyId: "16",
        name: "Toyota",
        score: "82",
        hqLocation: "Toyota City, Japan",
        revenueSize: "$15M",
        industry: "Car",
        insight: "Toyota is a global car manufacturer with a reputation for reliability and efficiency. It has introduced hybrid technology on a large scale and offers a wide range of vehicles to cater to various market segments.",
      },
      {
        companyId: "17",
        name: "Mercedes-Benz",
        score: "86",
        hqLocation: "Stuttgart, Germany",
        revenueSize: "$17M",
        industry: "Car",
        insight: "Mercedes-Benz is synonymous with luxury and prestige in the automotive world. The brand offers a range of vehicles known for their quality, safety features, and innovative technologies.",
      },
      {
        companyId: "18",
        name: "Honda",
        score: "76",
        hqLocation: "Tokyo, Japan",
        revenueSize: "$12M",
        industry: "Car",
        insight: "Honda is known for its reliable and fuel-efficient vehicles. The company produces a wide range of cars, motorcycles, and power equipment, showcasing a commitment to innovation and sustainability.",
      },
      {
        companyId: "19",
        name: "General Motors",
        score: "78",
        hqLocation: "Detroit, USA",
        revenueSize: "$13M",
        industry: "Car",
        insight: "General Motors is one of the oldest and largest car manufacturers in the world. With iconic brands like Chevrolet, GMC, and Cadillac, GM has played a pivotal role in shaping the automotive landscape.",
      },
      {
        companyId: "20",
        name: "Nissan",
        score: "72",
        hqLocation: "Yokohama, Japan",
        revenueSize: "$11M",
        industry: "Car",
        insight: "Nissan is a global automobile manufacturer recognized for its innovation and stylish designs. The company has contributed to advancements in electric and autonomous vehicle technology.",
      },
      {
        companyId: "21",
        name: "SpaceX",
        score: "92",
        hqLocation: "Hawthorne, USA",
        revenueSize: "$150M",
        industry: "Space",
        insight: "SpaceX, founded by Elon Musk, is a private aerospace manufacturer and space transportation company. It is known for its ambitious goals of reducing space transportation costs and enabling the colonization of Mars.",
      },
      {
        companyId: "22",
        name: "Nike",
        score: "87",
        hqLocation: "Beaverton, USA",
        revenueSize: "$36M",
        industry: "Sportswear",
        insight: "Nike is a global sportswear and athletic footwear brand. With iconic products like Air Jordan and its Just Do It slogan, Nike has a strong presence in sports and fashion.",
      },
      {
        companyId: "23",
        name: "Starbucks",
        score: "85",
        hqLocation: "Seattle, USA",
        revenueSize: "$26M",
        industry: "Coffee",
        insight: "Starbucks is a renowned coffeehouse chain known for its wide variety of coffee drinks and cozy atmosphere. The company has a global reach and is a symbol of premium coffee.",
      },
      {
        companyId: "24",
        name: "Boeing",
        score: "80",
        hqLocation: "Chicago, USA",
        revenueSize: "$95M",
        industry: "Aerospace",
        insight: "Boeing is a major aerospace company that designs, manufactures, and sells airplanes, rotorcraft, rockets, satellites, and more. It has a significant impact on aviation and space exploration.",
      },
      {
        companyId: "25",
        name: "McDonald's",
        score: "76",
        hqLocation: "Chicago, USA",
        revenueSize: "$37M",
        industry: "Fast Food",
        insight: "McDonald's is a global fast-food chain known for its signature burgers and golden arches. The company's affordability and convenience have made it a staple in many communities.",
      },
      {
        companyId: "26",
        name: "Adobe",
        score: "88",
        hqLocation: "San Jose, USA",
        revenueSize: "$13M",
        industry: "Software",
        insight: "Adobe is a software company that offers a wide range of creative and multimedia software solutions. Its products, including Photoshop, Illustrator, and Acrobat, have become industry standards.",
      },
      {
        companyId: "27",
        name: "Samsung",
        score: "83",
        hqLocation: "Seoul, South Korea",
        revenueSize: "$320M",
        industry: "Electronics",
        insight: "Samsung is a multinational conglomerate known for its electronics, including smartphones, TVs, and appliances. The company is a leader in technological innovation and has a global presence.",
      },
    ]
  }
}
